version: '3'

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meeting-website
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    container_name: database

  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: meeting-website
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
    container_name: server

  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    ports:
      - "8081:8081"
    container_name: client
